### ISSUE TITLE
Avoid using Pandoc

### ISSUE THREAD

**Issue by ilario** [con-f-use/bookletimposer#2]
Is Pandoc avoidable as a dependency?
I saw it is used just for converting the man page in format, could the man page document markup be converted to something that does not need Pandoc?
The problem is not Pandoc itself, rather the Haskell dependencies it pulls:
400 MB on my system.

**Comment by con-f-use** [comment]
You might want to ask this question here, if even still an issue in the upstream project: https://git.codecoop.org/kjo/bookletimposer

**Comment by ilario** [comment]
@con-f-use thanks for the suggestion. I already tried but I found no way to register an account there in order to write the issue report. And I wrote directly to Kjo but received no answer.

**Comment by con-f-use** [comment]
Did you try to simply comment out the `build_man` lines in `setup.py` and build the package without man pages?

https://git.codecoop.org/kjo/bookletimposer/-/blob/master/setup.py#L81
https://git.codecoop.org/kjo/bookletimposer/-/blob/master/setup.py#L121

Also pandoc and its Haskell  deps are only needed at built time, you can build the man pages once and then uninstall pandoc.

**Comment by ilario** [comment]
I just tried, thanks for the suggestion. It works.
I know I can deal with it easily removing the dependencies after building, but I was suggesting to change it in the code so that nobody has to do it nor I have to do it for every bookletimposer package upgrade (I'm on Arch Linux, and for every upgrade of bookletimposer I have to compile it).

**Comment by con-f-use** [comment]
The proper thing to do would be for the maintainers to setup up CI and build wheel packages for the different architectures to upload to pypi.org. No idea why they don't, though.
