### ISSUE TITLE
Migrate from pyPdf / PyPDF2 to pypdf

### ISSUE THREAD

**Issue by MartinThoma** [con-f-use/bookletimposer#3]
I've noticed that you still use/mention pyPdf / PyPDF2.

I'm the maintainer of both projects and we moved to `pypdf` (now written all-lowercase).

pypdf==3.1.0 is essentially the same as PyPDF2==3.0.0, but pypdf will receive updates and bugfixes.

Would you mind to mingrate bookletimposer to `pypdf`?

**Comment by con-f-use** [comment]
Thanks Martin for maintaining pypdf and actively caring about your userbase. However, I'm not maintaining bookletimposer. From the readme: 

> This is a rehost of the original Bookletimposer, with a very small change. Bookletimposer now opens the converted file automatically after its generation finished.
>
>The author of the whole original program is Kjö Hansi Glaz ([kjo@a4nancy.net.eu.org](mailto:kjo@a4nancy.net.eu.org)). The rehost was made because the original git repository is now unreachable. The hoster (con-f-use) is not associated with Kjö Hansi Glaz and would be happy to transfer ownership of this repository to him at his request.
>
> Edit: There is an active repository of the original now: https://git.codecoop.org/kjo/bookletimposer
